image: ruby:2.2

before_script:
  - apt-get install npm
  - npm install -g grunt
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

stages:
  - build

job1:
  stage: build
  script:
    - grunt build --force
  only:
    - master
  tags:
    - ruby
